before switching

diff --git a/bin/toggle-sound-device b/bin/toggle-sound-device
--- a/bin/toggle-sound-device
+++ b/bin/toggle-sound-device
@@ -6,27 +6,14 @@
 
 currentOuput=$(pactl info | awk '/Default Sink:/{ print $3 }')
 
+echo "Current output device is $currentOuput"
 laptopInputDevice='alsa_input.pci-0000_00_1f.3.analog-stereo.2'
-headsetInputDevice='alsa_output.usb-SteelSeries_SteelSeries_Arctis_7-00.stereo-game.2.monitor'
+headsetInputDevice='alsa_output.usb-SteelSeries_SteelSeries_Arctis_7-00.stereo-game.monitor'
 
 laptopOutputDevice='alsa_output.pci-0000_00_1f.3.analog-stereo.2'
 headsetOutputDevice='alsa_output.usb-SteelSeries_SteelSeries_Arctis_7-00.stereo-game.2'
 
-case $currentOuput in
-$headsetOutputDevice)
-    pactl set-default-sink $laptopOutputDevice
-    if [ $? != 0 ]; then
-        echo "Setting default output device to laptop has failed."
-        exit 1
-    fi
-    pactl set-default-source $laptopInputDevice
-    if [ $? != 0 ]; then
-        echo "Setting default input device to laptop has failed."
-        exit 1
-    fi
-    paplay /usr/share/sounds/gnome/default/alerts/swing.ogg
-    ;;
-$laptopOutputDevice)
+function headsetSound() {
     pactl set-default-sink $headsetOutputDevice
     if [ $? != 0 ]; then
         echo "Setting default output device to headset has failed."
@@ -37,12 +24,32 @@ $laptopOutputDevice)
         echo "Setting default input device to headset has failed."
         exit 1
     fi
-    paplay /usr/share/sounds/gnome/default/alerts/click.ogg
-    echo "If you hear nothing from the laptop, it means default sound output is your headset."
+}
+
+function laptopSound() {
+    pactl set-default-sink $laptopOutputDevice
+    if [ $? != 0 ]; then
+        echo "Setting default output device to laptop has failed."
+        exit 1
+    fi
+    pactl set-default-source $laptopInputDevice
+    if [ $? != 0 ]; then
+        echo "Setting default input device to laptop has failed."
+        exit 1
+    fi
+}
+
+case $currentOuput in
+$headsetOutputDevice)
+    headsetSound
+    ;;
+$laptopOutputDevice)
+    laptopSound
     ;;
 *)
-    echo $currentOuput is unknown
-    exit 1
+    echo "Unknown output device: $currentOuput"
+    echo "Setting default output device to laptop."
+    laptopSound
     ;;
 esac
 exit 0
